[package]
name = "vale-app"
description = "Vale desktop app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
vale-store.workspace = true
vale-style.workspace = true
vale-render.workspace = true
vale-sphere.workspace = true
vale-import.workspace = true
vale-labeler.workspace = true
vale-terrain = { workspace = true, features = ["gpu"] }
eframe.workspace = true
clap.workspace = true
anyhow.workspace = true
kurbo.workspace = true
bytemuck = "1.25.2"

[target.'cfg(not(target_os = "ios"))'.dependencies]
egui_kittest.workspace = true
image.workspace = true
rfd.workspace = true

[dev-dependencies]
tiff.workspace = true

[target.'cfg(target_os = "ios")'.dependencies]
objc2 = "0.6.5"
objc2-foundation = { version = "0.3.2", default-features = false, features = [
    "std",
    "NSArray",
    "NSSet",
    "NSEnumerator",
    "NSValue",
    "NSDate",
    "NSProcessInfo",
    "NSString",
    "NSURL",
] }
objc2-ui-kit = { version = "0.3.2", default-features = false, features = [
    "std",
    "objc2-core-foundation",
    "UIResponder",
    "UIView",
    "UITouch",
    "UIEvent",
    "UIGestureRecognizer",
    "UIGestureRecognizerSubclass",
    "UIHoverGestureRecognizer",
    "block2",
    "objc2-uniform-type-identifiers",
    "UIViewController",
    "UIDocumentPickerViewController",
] }
objc2-uniform-type-identifiers = { version = "0.3.2", default-features = false, features = [
    "std",
    "UTType",
] }

[[bin]]
name = "vale-app"
path = "src/main.rs"
