[package]
name = "vale-sphere"
description = "Sphere projections, clipping, and graticule for Vale"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
kurbo.workspace = true
proj.workspace = true

[dev-dependencies]
serde_json.workspace = true
